# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c139b6c529852889e8a2d30da9cab004360f3e3c0fc6b90e4485aa1ce3ef6f502404cbc46bd1197fa4c443968b6cecc83f247da9dbb26a848aa0081254321f3d

test:
  secret_key_base: 08c4fa3f23ea6d8eb832a934761058d868d3255735ce3a441020b452b557351901e1dfbbccb0f2c1976f39e48684d7b6702ac46a4ea1ce6fa352fdf806627445

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
